//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestForRepairWPF.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RequestForRepairEntities : DbContext
    {
        private static DB_RequestForRepairEntities _context;

        public DB_RequestForRepairEntities()
            : base("name=DB_RequestForRepairEntities")
        {
        }
    
        public static DB_RequestForRepairEntities GetContext()
        {
            if (_context == null)
                _context = new DB_RequestForRepairEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<DescriptionRoom> DescriptionRoom { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfAccount> TypeOfAccount { get; set; }
        public virtual DbSet<TypeRoom> TypeRoom { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Software> Software { get; set; }
        public virtual DbSet<SpecialEquipment> SpecialEquipment { get; set; }
        public virtual DbSet<TechnicalEquipment> TechnicalEquipment { get; set; }
        public virtual DbSet<U_R_Room> U_R_Room { get; set; }
    }
}
